## Numpy array creation

In [1]:
import numpy as np

### arange()

In [2]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# stepping
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## zeros(): arrays with all zeros

In [5]:
"""
zeros(shape,dtype=float,order='c',*,like=none)
returns a new array of given shape and type, filled with zeros.
"""
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
# 2D array
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
# 3D array
np.zeros((2,3,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [10]:
# if i want integer zero then?
np.zeros((2,6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## ones(): all 1's in array

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones((3,4,6), dtype=int) # for convertinng from float to integer vallue i.e. 1 

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

## empty array

In [19]:
np.empty((4,2)) # it returns garbage values 

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 9.58487353e-321],
       [8.01097888e-307, 8.01094493e-307]])

In [20]:
np.empty((3,4,5), dtype=str)

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

## supply own value in array

In [21]:
# signature: np.full(shape, fill_value, dtype, order='c', *, like=None )

In [1]:
# return a new array of given shape and type without usihng fill_type
import numpy as np

In [2]:
np.full((3,3),fill_value=100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [3]:
np.full((10),fill_value=-1.2)

array([-1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2])

In [4]:
np.full((3,3),fill_value=False)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [5]:
np.full((3,3),fill_value='null')

array([['null', 'null', 'null'],
       ['null', 'null', 'null'],
       ['null', 'null', 'null']], dtype='<U4')

## empty(): Array with garbage values

In [6]:
np.empty(5) #1D

array([2.12199579e-314, 4.67296746e-307, 5.59282311e-321, 9.42166132e-312,
       3.72364679e-317])

In [7]:
np.empty((6,4)) #2D

array([[9.43180277e-312, 7.80623720e-322, 0.00000000e+000,
        0.00000000e+000],
       [7.56587583e-307, 1.15998412e-028, 4.31603868e-080,
        1.94919985e-153],
       [1.35717430e+131, 1.05894612e-153, 6.40695294e+029,
        4.07356379e+223],
       [8.94213159e+130, 6.40695294e+029, 3.88834045e+160,
        1.81148490e-152],
       [8.59641098e+030, 3.88834045e+160, 1.16304910e+214,
        2.18229367e-094],
       [1.43267083e+161, 2.20832505e-094, 9.80058441e+252,
        1.23971686e+224]])

In [8]:
np.empty((2,3,3)) #3D

array([[[1.37962049e-306, 1.24610791e-306, 1.11260959e-306],
        [1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
        [1.78019082e-306, 4.45061456e-308, 1.24612081e-306]],

       [[1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
        [1.78019625e-306, 1.11255866e-306, 8.90098127e-307],
        [9.34609790e-307, 3.91792279e-317, 2.56761491e-312]]])

## identity(): Identity matrix


#### diagonal elements are 1 and non-diagonal elements are zero

In [9]:
#n : means NxN array

In [10]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [12]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
np.identity((2,3),dtype=int)

TypeError: 'tuple' object cannot be interpreted as an integer

## eye(): used to an create identity matrix

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.eye?

In [16]:
#identity(N, dtype=None, *, like=None)
#eye(N, M=None, k=0, dtype=<class 'float'>)
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [17]:
np.eye(4,6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

#Q. Difference between identity() and eye()?
- both returns identity matrix
- identity(): it takes only one argument ie a Number only for row and bydefault same number of columns as it is a identity matrix.
- eye(): it allows to put number of rows and columns of users choice. it also allows to change the position identity 1 in the matrix.


## linspace(): Array with linearly spaced values

-Space between two consequtive numbers will be same always

In [18]:
np.linspace?

In [20]:
"""
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,)


"""""



'\nnp.linspace(\n    start,\n    stop,\n    num=50,\n    endpoint=True,\n    retstep=False,\n    dtype=None,\n    axis=0,)\n\n\n'

In [21]:
np.linspace(3)

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

In [22]:
np.linspace(3,4)

array([3.        , 3.02040816, 3.04081633, 3.06122449, 3.08163265,
       3.10204082, 3.12244898, 3.14285714, 3.16326531, 3.18367347,
       3.20408163, 3.2244898 , 3.24489796, 3.26530612, 3.28571429,
       3.30612245, 3.32653061, 3.34693878, 3.36734694, 3.3877551 ,
       3.40816327, 3.42857143, 3.44897959, 3.46938776, 3.48979592,
       3.51020408, 3.53061224, 3.55102041, 3.57142857, 3.59183673,
       3.6122449 , 3.63265306, 3.65306122, 3.67346939, 3.69387755,
       3.71428571, 3.73469388, 3.75510204, 3.7755102 , 3.79591837,
       3.81632653, 3.83673469, 3.85714286, 3.87755102, 3.89795918,
       3.91836735, 3.93877551, 3.95918367, 3.97959184, 4.        ])

In [23]:
np.linspace(3,5,num=33,dtype=int)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5])

In [24]:
np.linspace(5,7,num=23,retstep=True)

(array([5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
        5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
        5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
        6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727273,
        6.81818182, 6.90909091, 7.        ]),
 0.09090909090909091)

In [27]:
# if we dont want to add endpoint in our array then?
x = np.linspace(5,7,num=23,endpoint=False)

In [28]:
np.diagonal(x)

ValueError: diag requires an array of at least two dimensions

In [29]:
x = np.array((3,3,3))

In [30]:
np.diagonal(x) # gives you an access to diagonal elements 

ValueError: diag requires an array of at least two dimensions

In [31]:
k = np.identity(4)

In [32]:
k

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.diagonal(k)

array([1., 1., 1., 1.])

## random(): Creates an array of random numbers

In [34]:
#random(size=None)
#return random floats in the half-open interval[0.0,1.0]
np.random.random(5)

array([0.86428937, 0.50262276, 0.92360185, 0.26482116, 0.02288308])

In [36]:
np.random.random((4,5))

array([[0.24983279, 0.25687547, 0.70202782, 0.8459854 , 0.80044759],
       [0.77067317, 0.08398698, 0.71031504, 0.94706613, 0.74383402],
       [0.29145441, 0.55131053, 0.97833476, 0.48785093, 0.7306244 ],
       [0.07879028, 0.38269772, 0.1337926 , 0.89587136, 0.09248281]])

In [37]:
np.random.random?

In [39]:
# random integer values 
#random.randint(low,high=None,size=None,dtype=int)
np.random.randint(4,size=12)

array([0, 1, 2, 2, 1, 1, 1, 2, 1, 0, 1, 1])

In [40]:
np.random.randint(5,size=10) # when we supply only low then it is exclusive 

array([1, 1, 3, 3, 1, 0, 3, 3, 1, 4])

In [41]:
np.random.randint(5,9,size=20) #when we supply both low and High values then it includes low but excludes High

array([6, 8, 5, 7, 8, 5, 8, 7, 7, 5, 7, 7, 8, 5, 7, 5, 5, 7, 6, 6])

In [42]:
# Generate a data of Bloodpressure in range 70-120
np.random.randint(70,121,size=100)

array([115, 111,  88, 116, 103, 102,  99, 116,  72, 117,  87, 101, 120,
        78, 110,  84,  73, 100,  72,  74, 108,  77,  75, 102,  83,  82,
        74, 100,  96,  95, 112,  87, 110, 107,  73,  87,  89, 112, 107,
        85,  95, 106, 114,  70,  86, 109,  71,  85,  94, 118, 101,  95,
       102, 114,  91,  85, 108,  93,  75, 100,  80, 100,  95, 115,  88,
        89,  83,  99,  91,  79, 104,  72, 120,  82,  75,  83,  93, 100,
        91,  77, 106,  94,  73,  89,  81,  93, 112, 102,  80,  79,  86,
       111, 105, 108, 109, 107,  83, 111,  82, 111])

In [43]:
# salaray data: for 20000, 60000 for 100 employees
np.random.randint(20000,60001,100)

array([53505, 30443, 39683, 35821, 53905, 50823, 43701, 35358, 53511,
       44195, 43334, 31532, 59162, 35960, 58653, 43604, 30321, 36010,
       40921, 30371, 22769, 52836, 20287, 33789, 23810, 26325, 58391,
       54720, 53359, 22282, 40904, 31098, 45442, 52375, 51229, 51846,
       40037, 54778, 47116, 25433, 51288, 44872, 39219, 34354, 24127,
       44423, 59365, 28676, 21900, 32881, 22842, 21567, 52301, 34190,
       50047, 47643, 47563, 33154, 33202, 33356, 57859, 30277, 22886,
       37554, 31287, 21374, 48254, 30407, 29491, 57846, 51285, 31915,
       24663, 32699, 22798, 47325, 45895, 47175, 38682, 53172, 32484,
       50987, 58931, 26685, 41883, 20205, 43289, 41305, 47946, 26172,
       23587, 34197, 30870, 29534, 32383, 38033, 59103, 29844, 46333,
       49442])

In [48]:
# if we have a array present in our directory
x

array([3, 3, 3])

In [50]:
y = np.random.random((5,3))

In [51]:
y

array([[0.42420855, 0.23473876, 0.99374867],
       [0.3390831 , 0.52914767, 0.67218166],
       [0.97566423, 0.25338003, 0.08091377],
       [0.32080216, 0.46047979, 0.28195951],
       [0.91419746, 0.07324572, 0.415479  ]])

In [52]:
y.shape

(5, 3)

In [53]:
# Create an array of 1's with same structure as that of y
np.ones_like(y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.ones_like(y,dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [55]:
np.zeros_like(y,dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
np.empty_like(y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.empty_like(y,dtype=int)

array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       [      0,    1944,       0],
       [      0, 7077985,       0]])

## typecasting in numpy

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(10).dtype

dtype('int32')

In [60]:
np.arange(10,dtype=float).dtype

dtype('float64')

In [61]:
# 8 bit = 1 byte 
# 32 bit = 4 bytes
# 64 bit = 8 bytes

In [62]:
np.arange(10,dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
np.arange(10, dtype='float16') # in bits

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [65]:
np.arange(20, dtype='f') # f for float 32

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [66]:
np.arange(20, dtype='f4')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [67]:
np.arange(20, dtype='f8')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [68]:
np.arange(20, dtype='i4') # i4 means integer32bits 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
np.arange(20, dtype='int64')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [70]:
np.arange(20, dtype='int32')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [80]:
np.arange(20, dtype='int64')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [81]:
np.arange(20, dtype='i8')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

## after creation of an array if we want to typecast it then?

In [82]:
s = np.arange(20)

In [83]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [84]:
s.dtype

dtype('int32')

### use astype()

In [85]:
s.astype('i8')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)