In [1]:
import numpy as np

In [2]:
# I want 4x4 numpy array whhose all values set to true 
np.full((4,4), fill_value=True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [3]:
np.ones((4,4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [4]:
# I want 4x4 numpy array whose all values set to False
np.full((4,4), fill_value=False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [5]:
np.zeros((4,4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [6]:
# Now, I want 4x4 numppy array whose diagonal values are set to True and non-diagonal values to False
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [7]:
np.eye(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [8]:
#Assignment: I want 4x4 numpy array whose diagonal value set to False and non diagonal True
~np.identity(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

## Check different properties of numpy array

In [9]:
a = np.random.random((4,4))

In [10]:
a


array([[0.83825568, 0.56444137, 0.75492952, 0.60682561],
       [0.37515507, 0.23800999, 0.24324307, 0.32894522],
       [0.61066947, 0.54393083, 0.11806239, 0.6479753 ],
       [0.79730048, 0.60447705, 0.41368138, 0.41436823]])

In [11]:
# total elements present 
a.size

16

In [12]:
# check shape
a.shape

(4, 4)

In [13]:
#(4, 4) 4 rows, 4 columns  

In [14]:
print('Total number of rows',a.shape[0])
print('Total number of columns',a.shape[1])

Total number of rows 4
Total number of columns 4


In [15]:
# memory in bytes to each element
a.itemsize

8

In [16]:
# check datatype 
a.dtype

dtype('float64')

In [17]:
# check a memory 
a.data

In [18]:
# check dimension 
a.ndim

2

In [19]:
# 2 means 2Dimensional 

## Shape manipulation 

In [20]:
print(a)
print(a)
print('Abhishek')

[[0.83825568 0.56444137 0.75492952 0.60682561]
 [0.37515507 0.23800999 0.24324307 0.32894522]
 [0.61066947 0.54393083 0.11806239 0.6479753 ]
 [0.79730048 0.60447705 0.41368138 0.41436823]]
[[0.83825568 0.56444137 0.75492952 0.60682561]
 [0.37515507 0.23800999 0.24324307 0.32894522]
 [0.61066947 0.54393083 0.11806239 0.6479753 ]
 [0.79730048 0.60447705 0.41368138 0.41436823]]
Abhishek


In [21]:
display(a,a,'Abhi')

array([[0.83825568, 0.56444137, 0.75492952, 0.60682561],
       [0.37515507, 0.23800999, 0.24324307, 0.32894522],
       [0.61066947, 0.54393083, 0.11806239, 0.6479753 ],
       [0.79730048, 0.60447705, 0.41368138, 0.41436823]])

array([[0.83825568, 0.56444137, 0.75492952, 0.60682561],
       [0.37515507, 0.23800999, 0.24324307, 0.32894522],
       [0.61066947, 0.54393083, 0.11806239, 0.6479753 ],
       [0.79730048, 0.60447705, 0.41368138, 0.41436823]])

'Abhi'

In [22]:
# shape
a.shape

(4, 4)

In [23]:
# (4, 4) means 4rows x 4columns = 16 elements
# for making a 2D array, we have following different options whose multiplication returns 16 
#(1, 16)
#(2, 8)
#(8, 2)
#(4, 4)
#(16, 1)
# for making an 3D array from 16 elements we have options like: 
#(1,4,4) # 1*4*4=16
#(2,2,4) # 2*2*4=16
#(4,2,2) # 4*2*2=16

## reshape(): It changes the shape temporarily 

In [24]:
a.reshape(1,16)

array([[0.83825568, 0.56444137, 0.75492952, 0.60682561, 0.37515507,
        0.23800999, 0.24324307, 0.32894522, 0.61066947, 0.54393083,
        0.11806239, 0.6479753 , 0.79730048, 0.60447705, 0.41368138,
        0.41436823]])

In [25]:
a.reshape(2, 8)

array([[0.83825568, 0.56444137, 0.75492952, 0.60682561, 0.37515507,
        0.23800999, 0.24324307, 0.32894522],
       [0.61066947, 0.54393083, 0.11806239, 0.6479753 , 0.79730048,
        0.60447705, 0.41368138, 0.41436823]])

In [26]:
a.reshape(8, 2)

array([[0.83825568, 0.56444137],
       [0.75492952, 0.60682561],
       [0.37515507, 0.23800999],
       [0.24324307, 0.32894522],
       [0.61066947, 0.54393083],
       [0.11806239, 0.6479753 ],
       [0.79730048, 0.60447705],
       [0.41368138, 0.41436823]])

In [28]:
# 3D using reshape 
a.reshape(1,4,4)

array([[[0.83825568, 0.56444137, 0.75492952, 0.60682561],
        [0.37515507, 0.23800999, 0.24324307, 0.32894522],
        [0.61066947, 0.54393083, 0.11806239, 0.6479753 ],
        [0.79730048, 0.60447705, 0.41368138, 0.41436823]]])

In [29]:
a.reshape(2,2,4)

array([[[0.83825568, 0.56444137, 0.75492952, 0.60682561],
        [0.37515507, 0.23800999, 0.24324307, 0.32894522]],

       [[0.61066947, 0.54393083, 0.11806239, 0.6479753 ],
        [0.79730048, 0.60447705, 0.41368138, 0.41436823]]])