In [1]:
import numpy as np

In [2]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [4]:
np.arange(1,25).reshape(4,6) #row major

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [6]:
np.arange(1,25).reshape(4,6,order='F') #column major

array([[ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23],
       [ 4,  8, 12, 16, 20, 24]])

In [7]:
a =np.arange(1,25).reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [8]:
b = np.arange(1,25)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [9]:
b.reshape(6,4,order = 'F')

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [10]:
b.reshape(6,4,order='C')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [13]:
# b is unchanged. ie reshape() is temporary unless you assign changes to new variable
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
b1 = b.reshape(6,4,order='C')

In [16]:
b1 # now the b is changed 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

## conditional based selection

In [17]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [18]:
# fetch values greater than 10 (>10)
a>10
#performs elementwise operation
# returns array with an boolean output

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [19]:
# boolean indexing is supported
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [22]:
# concept of boolean indexing
# now, total 4 rows present in 'a'
# indexing works on rows: and we are supplying boolean index
a[[True,False,True,False]]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

In [23]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [24]:
# more than one condition we want to test
# fetch values divisible by 5 and 7
a % 5 == 0

array([[False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False],
       [False,  True, False, False, False, False]])

In [25]:
a % 7 == 0

array([[False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False]])

In [26]:
# logical and, or, not
# bitwise (&)and, |(or), ~(not), ^(XOR)

In [27]:
(a % 5 == 0) | (a % 7 == 0)

array([[False, False, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [False,  True,  True, False, False, False]])

In [28]:
a[(a % 5 == 0) | (a % 7 == 0)]

array([ 5,  7, 10, 14, 15, 20, 21])

In [29]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [33]:
# Fetch values divisible by 5 and 10
a[(a % 5 == 0) & (a % 10 == 0)]

array([10, 20])

In [36]:
 #XOR:-
#00 0
#01 1
#10 1
#11 0

In [37]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [38]:
# fetch values greater than 18
a[a>18]

array([19, 20, 21, 22, 23, 24])

## can we compare two arrays??

In [40]:
x = np.array([[2,3],[4,5]])
x

array([[2, 3],
       [4, 5]])

In [41]:
y = np.array([[10,20],[6,7]])
y

array([[10, 20],
       [ 6,  7]])

In [42]:
x > y

array([[False, False],
       [False, False]])

In [43]:
x < y

array([[ True,  True],
       [ True,  True]])

## scaler mathematics over numpy array

In [44]:
x

array([[2, 3],
       [4, 5]])

In [45]:
y

array([[10, 20],
       [ 6,  7]])

In [46]:
x

array([[2, 3],
       [4, 5]])

In [49]:
# add 10 to each element
x + 10
# this result is temporary. To make it permanant assign it a new variable or use Assignment operator

array([[12, 13],
       [14, 15]])

In [52]:
x += 10 # now the x will changed permanantly

In [53]:
x

array([[22, 23],
       [24, 25]])

In [54]:
# using numpy(np) add 100
np.add(x,100) # temporary output

array([[122, 123],
       [124, 125]])

In [55]:
# if you want to do the addition of x and y [vector addition]?
np.add(x,y)

array([[32, 43],
       [30, 32]])

In [56]:
display(x,y)
np.add(x,y)

array([[22, 23],
       [24, 25]])

array([[10, 20],
       [ 6,  7]])

array([[32, 43],
       [30, 32]])

In [57]:
x += y

In [58]:
x

array([[32, 43],
       [30, 32]])

In [59]:
y

array([[10, 20],
       [ 6,  7]])

In [60]:
# x += y : it changes x permanantly by adding values from y array [vector addition]


In [63]:
np.subtract(x,y) #[vector substraction]

array([[22, 23],
       [24, 25]])

In [64]:
np.divide(x,y) # [vector divison] 

array([[3.2       , 2.15      ],
       [5.        , 4.57142857]])

In [65]:
np.multiply(x,y) # [vector multiplication]

array([[320, 860],
       [180, 224]])

In [66]:
np.floor_divide(x,y) # [vector floor division]

array([[3, 2],
       [5, 4]], dtype=int32)

In [67]:
np.mod(x,y)

array([[2, 3],
       [0, 4]], dtype=int32)

In [68]:
np.power(x,y)

array([[          0, -1616646287],
       [  729000000,           0]], dtype=int32)

## i want an 4x4 array in which all values must be True

In [69]:
np.full((4,4),True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [75]:
np.ones((4,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## i want 4x4 array in which all values must be False 

In [76]:
np.full((4,4),False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [77]:
np.zeros((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## We want an array 4 X 4 in whcih diagonal values must be True and non diagonal False



In [79]:
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

## We want an array 4 X 4 in whcih diagonal values must be False and non diagonal True

In [82]:
e = np.identity(4, dtype=int)
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [84]:
e1 = np.invert(e)
e1

array([[-2, -1, -1, -1],
       [-1, -2, -1, -1],
       [-1, -1, -2, -1],
       [-1, -1, -1, -2]], dtype=int32)

In [85]:
e1.astype(bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [86]:
e = ~np.identity(4, dtype=int)

In [87]:
e

array([[-2, -1, -1, -1],
       [-1, -2, -1, -1],
       [-1, -1, -2, -1],
       [-1, -1, -1, -2]], dtype=int32)

In [88]:
e = ~np.identity(4,dtype=bool)

In [89]:
e

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

## np.where()

In [90]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

### convert values>12 as 1 and values<12 as 0

In [91]:
# np.where(condition, return x if True , else y)
np.where(a>12,1,0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [92]:
np.where(a>12,True,False)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [95]:
# square values if it %5 == 0 (divisible by 5)
np.where(a%5==0,a**2,-a)
# values divisible by 5 ==> square them
# values not divisible by 5==> make them -ve

array([[ -1,  -2,  -3,  -4,  25,  -6],
       [ -7,  -8,  -9, 100, -11, -12],
       [-13, -14, 225, -16, -17, -18],
       [-19, 400, -21, -22, -23, -24]])

In [96]:
condition = np.array(['on','off','on','on','off'])
condition

array(['on', 'off', 'on', 'on', 'off'], dtype='<U3')

In [97]:
# convert 'on' as 1 and 'off' as 0
np.where(condition=='on',1,0)

array([1, 0, 1, 1, 0])

## spliting of array

In [98]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [99]:
# split an array into multiple sub-arrays as views into `ary
np.split(a,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [101]:
a1,a2,a3,a4=np.split(a,4) # unpacking

In [102]:
display(a1,a2,a3,a4)

array([[1, 2, 3, 4, 5, 6]])

array([[ 7,  8,  9, 10, 11, 12]])

array([[13, 14, 15, 16, 17, 18]])

array([[19, 20, 21, 22, 23, 24]])

In [103]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [104]:
np.split(a,3) #odd distribution is not allowed

ValueError: array split does not result in an equal division

### columnwise split

In [105]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [106]:
np.split(a,4,axis=1)

ValueError: array split does not result in an equal division

In [107]:
a = a.reshape(6,4)

In [108]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [110]:
np.split(a,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [111]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [112]:
a = a.reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [113]:
np.split(a,2,axis=1)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [114]:
np.hsplit(a,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [116]:
np.vsplit(a,4)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])